#!/usr/bin/env python3

# Copyright (c) 2021-2021 by the parties listed in the AUTHORS file.
# All rights reserved.  Use of this source code is governed by
# a BSD-style license that can be found in the LICENSE file.

"""Plot global timing results
"""

from pprint import PrettyPrinter
import sys
import argparse
import re

import csv

import numpy as np

import pandas as pd

import plotly.express as px


def main():
    parser = argparse.ArgumentParser(description="Plot a timing dump.")

    parser.add_argument(
        "--file",
        required=True,
        help="Name of input CSV file",
    )

    parser.add_argument(
        "--out",
        required=False,
        default="timing.pdf",
        help="Name of output file",
    )

    args = parser.parse_args()

    print(f"Reading input timing from {args.file}")

    raw = dict()
    n_column = 0

    with open(args.file, "r") as f:
        reader = csv.reader(f)
        for row in reader:
            name = row[0]
            mat = re.match(r"\(function\) (.*)", name)
            if mat is not None:
                # this is a function timer
                trace = mat.group(1)
                med = float(row[7])
                levels = trace.split("|")
                n_column = max(n_column, len(levels))
                raw[trace] = med

    # Compute untracked time.  For plotting, we add an "Other" category that
    # contains the total minus all the tracked sub-categories.

    subtotals = dict()
    for trace, val in raw.items():
        levels = trace.split("|")
        parent = "|".join(levels[:-1])
        if parent == "":
            parent = "ROOT"
        if parent not in subtotals:
            subtotals[parent] = 0.0
        subtotals[parent] += val

    for trace in list(raw.keys()):
        if trace in subtotals:
            # This is a "parent" counter with at least one child.
            other = raw[trace] - subtotals[trace]
            othername = f"{trace}|Other"
            del raw[trace]
            raw[othername] = other

    # Build the data needed for plotting

    lnames = [f"level{x}" for x in range(n_column)]
    data = list()

    for trace, val in raw.items():
        levels = trace.split("|")
        n_cols = len(levels)
        rlist = list()
        for i in range(n_cols):
            rlist.append(levels[i])
        if n_cols < n_column:
            for i in range(n_cols, n_column):
                rlist.append(None)
        rlist.append(val)
        data.append(rlist)

    cnames = list(lnames)
    cnames.append("value")
    print(f"{len(cnames)} columns = {cnames}")
    print(f"data = ")
    for row in data:
        print(f" {len(row)}: {row}")
    df = pd.DataFrame(data=data, columns=cnames)

    fig = px.sunburst(
        data_frame=df,
        path=lnames,
        values="value",
        title="TOAST Timing",
        height=700,
        template="plotly",
        branchvalues="total",
    )
    fig.write_image(args.out)


if __name__ == "__main__":
    main()
