#!/bin/bash

outdir="out_@@size@@_ground"
mkdir -p "${outdir}"

# This script assumes that you have toast and all dependencies
# installed and loaded in your environment.

# Generate the focalplane file if it does not already exist.

detpix=@@detpix@@

fpfile="${outdir}/fp_${detpix}.pkl"
fpparfile="@@topdir@@/params/ground/focalplane.par"

if [ ! -e "${fpfile}" ]; then
    toast_fake_focalplane.py @$fpparfile \
         --out "${outdir}/fp" --minpix $detpix
fi

# Generate the schedule file if it does not already exist.

schparfile="@@topdir@@/params/ground/schedule.par"

schedulefile="${outdir}/schedule.txt"

if [ ! -e "${schedulefile}" ]; then
    toast_ground_schedule.py @$schparfile \
         --out "${schedulefile}" --patch @@patch@@ \
         --stop @@schedule_stop@@
fi

# The executable script

ex=$(which toast_ground_sim.py)
echo "Using ${ex}"

# Scan strategy parameters from a file

parfile="@@topdir@@/params/ground/ground_sim.par"

# Data distribution parameters

# The commandline

com="${ex} @${parfile} \
--fp ${fpfile} \
--schedule ${schedulefile} \
--out ${outdir}/out \
--atm_cache ${outdir}/atm_cache \
--atm_xstep @@cellsize@@ \
--atm_ystep @@cellsize@@ \
--atm_zstep @@cellsize@@ \
"

# Use 2 processes, each with 2 threads

procs=2
threads=2

export OMP_NUM_THREADS=${threads}

run="mpirun -np ${procs}"

echo "${run} ${com}"
eval ${run} ${com} > "${outdir}/log" 2>&1
