#!/bin/bash

export OMP_TARGET_OFFLOAD=MANDATORY
export OMP_DISPLAY_ENV=verbose

#export LIBOMPTARGET_INFO=$((0x1 | 0x2 | 0x4 | 0x8 | 0x10 | 0x20))
export LIBOMPTARGET_INFO=-1
export LIBOMPTARGET_DEVICE_RTL_DEBUG=3

#export HSA_IGNORE_SRAMECC_MISREPORT=1

eval "$@"

# OMP_NUM_THREADS=4 OMP_TARGET_OFFLOAD=MANDATORY OMP_DISPLAY_ENV=verbose LIBOMPTARGET_INFO=-1 LIBOMPTARGET_DEVICE_RTL_DEBUG=3 TOAST_LOGLEVEL=VERBOSE TOAST_GPU_OPENMP=1 toast_mini --node_mem_gb 7 2>&1 | tee log