# In general, we try to run on:
# - The oldest supported python
# - The latest stable python that is the common default on most systems and conda
# - (During transitions) The newly released bleeding edge python

name:  Run Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests on ${{ matrix.arch }} with Conda Python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
            arch: Linux-x86_64
            ompdisable: 0
          - os: ubuntu-latest
            python: "3.12"
            arch: Linux-x86_64
            ompdisable: 0
          - os: ubuntu-latest
            python: "3.13"
            arch: Linux-x86_64
            ompdisable: 0
          - os: macos-latest
            python: "3.10"
            arch: MacOSX-x86_64
            ompdisable: 1
          - os: macos-latest
            python: "3.13"
            arch: MacOSX-x86_64
            ompdisable: 1
          - os: macos-latest
            python: "3.10"
            arch: MacOSX-arm64
            ompdisable: 1
          - os: macos-latest
            python: "3.13"
            arch: MacOSX-arm64
            ompdisable: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: true
          auto-update-conda: true
          auto-activate: true
          activate-environment:  # Disable creation of the 'test' env

      - name: Check Conda Config
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Create Conda Env
        run: |
          ./conda_setup.sh -e toast -p ${{ matrix.python }} -x
          conda activate toast
          python3 -m pip install 'spt3g==1.0.0'

      - name: Install
        run: |
          conda activate toast
          pip install -v .

      - name: Run Serial Tests
        run: |
          conda activate toast
          export OMP_NUM_THREADS=2
          export MPI_DISABLE=1
          python3 -c 'import toast.tests; toast.tests.run()'
          unset MPI_DISABLE
          unset OMP_NUM_THREADS

      - name: Run MPI Tests
        run: |
          conda activate toast
          export OMP_NUM_THREADS=1
          mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
          unset OMP_NUM_THREADS

