
name:  Binary Wheels

on:
  workflow_dispatch:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.builder }}_${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails.  Useful for
      # debugging multiple problems in parallel.
      fail-fast: false
      matrix:
        include:
          # Linux 64 bit manylinux
          - os: ubuntu-latest
            arch: x86_64
            python: 310
            builder: manylinux
          - os: ubuntu-latest
            arch: x86_64
            python: 311
            builder: manylinux
          - os: ubuntu-latest
            arch: x86_64
            python: 312
            builder: manylinux
          - os: ubuntu-latest
            arch: x86_64
            python: 313
            builder: manylinux

          # MacOS x86_64.
          - os: macos-15-intel
            arch: x86_64
            python: 310
            builder: macosx
            deploy: 15.0
          - os: macos-15-intel
            arch: x86_64
            python: 311
            builder: macosx
            deploy: 15.0
          - os: macos-15-intel
            arch: x86_64
            python: 312
            builder: macosx
            deploy: 15.0
          - os: macos-15-intel
            arch: x86_64
            python: 313
            builder: macosx
            deploy: 15.0

          # MacOS arm64
          - os: macos-15
            arch: arm64
            python: 310
            builder: macosx
            deploy: 15.0
          - os: macos-15
            arch: arm64
            python: 311
            builder: macosx
            deploy: 15.0
          - os: macos-15
            arch: arm64
            python: 312
            builder: macosx
            deploy: 15.0
          - os: macos-15
            arch: arm64
            python: 313
            builder: macosx
            deploy: 15.0
    env:
      CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.builder }}_${{ matrix.arch }}
      CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.builder }}_2_28
      CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.builder }}_2_28
      CIBW_BUILD_VERBOSITY: 3
      CIBW_ENVIRONMENT_LINUX: >
        CMAKE_ARGS="-DBLAS_LIBRARIES='-L/usr/local/lib -lopenblas -fopenmp -lm -lgfortran' -DLAPACK_LIBRARIES='-L/usr/local/lib -lopenblas -fopenmp -lm -lgfortran' -DTOAST_STATIC_DEPS=ON -DFFTW_ROOT=/usr/local -DAATM_ROOT=/usr/local -DSUITESPARSE_INCLUDE_DIR_HINTS=/usr/local/include -DSUITESPARSE_LIBRARY_DIR_HINTS=/usr/local/lib"
      CIBW_ENVIRONMENT_MACOS: >
        MACOSX_DEPLOYMENT_TARGET=${{ matrix.deploy }}
        CMAKE_ARGS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS='-O3 -fPIC' -DCMAKE_CXX_FLAGS='-O3 -fPIC -std=c++11 -stdlib=libc++' -DDISABLE_OPENMP=1 -DBLAS_LIBRARIES='/usr/local/lib/libopenblas.dylib' -DLAPACK_LIBRARIES='/usr/local/lib/libopenblas.dylib' -DFFTW_ROOT=/usr/local -DAATM_ROOT=/usr/local -DSUITESPARSE_INCLUDE_DIR_HINTS=/usr/local/include -DSUITESPARSE_LIBRARY_DIR_HINTS=/usr/local/lib"
      CIBW_BEFORE_BUILD_LINUX: ./packaging/wheels/install_deps_linux.sh
      CIBW_BEFORE_BUILD_MACOS: ./packaging/wheels/install_deps_osx.sh
      CIBW_BEFORE_TEST: export OMP_NUM_THREADS=2
      CIBW_TEST_COMMAND_LINUX: >
        tst=$(dirname $(python -c 'import toast; print(toast.__file__)')) &&
        echo "Toast test install at ${tst}" &&
        ldd ${tst}/_libtoast.cpython* &&
        eval {project}/packaging/wheels/cibw_run_tests.sh ${{ matrix.os }}
      CIBW_TEST_COMMAND_MACOS: >
        tst=$(dirname $(python -c 'import toast; print(toast.__file__)')) &&
        echo "Toast test install at ${tst}" &&
        otool -L ${tst}/_libtoast.cpython* &&
        eval {project}/packaging/wheels/cibw_run_tests.sh ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==3.4.1

      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels_cp${{ matrix.python }}-${{ matrix.builder }}_${{ matrix.arch }}
          path: ./wheelhouse/toast*cp${{ matrix.python }}-${{ matrix.builder }}*${{ matrix.arch }}*.whl

  upload_pypi:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v8
        with:
          # Unpacks all artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
